### ISSUE TITLE
Update plugin description

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-starting-affiliate-id#17]
The current plugin description is (https://github.com/AffiliateWP/affiliatewp-starting-affiliate-id/blob/release/1.0.0/affiliatewp-starting-affiliate-id.php#L5):

> Change the starting affiliate ID of your affiliate network.

I think we should avoid the use of "network" as it could imply an affiliate network such as Shareasale or a multi-site network.

Proposed text using `program`:

> Change the starting affiliate ID of your affiliate program.

Also need to change this in the plugin's readme.txt, even though it doesn't look like wordpress.org is using the text anymore for the plugin's description.

> This add-on for AffiliateWP allows you specify the starting affiliateID for your affiliate network.

Proposed (extra space and word change):

> This add-on for AffiliateWP allows you specify the starting affiliate ID for your affiliate program.

**Comment by amdrew** [comment]
PR: https://github.com/AffiliateWP/affiliatewp-starting-affiliate-id/pull/18

**Comment by DrewAPicture** [comment]
Merged #18.
